#!/usr/bin/env bash

apt-get update
apt-get install build-essential \
				python-dev \
				python-pip \
				memcached \
				libmemcached-dev \
				apache2-utils

pip install cython

/etc/init.d/memcached stop
update-rc.d -f memcached remove

echo
echo "Done."
echo
